### ISSUE TITLE
AsyncIO Executor

### ISSUE THREAD

**Issue by AlecAivazis** [graphql-python/graphql-core-legacy#63]
I've run into a bug with the AsyncIO Executor when trying to run a query from an application where the event is running. 

I think it's because the executor's implemention of `wait_until_complete` uses `run_until_complete` which starts up the event loop and waits. Since the event loop is already running, it threw an exception when I tried to start it a second time.

**Comment by syrusakbary** [comment]
I've added the `loop` option in `AsyncioExecutor`, now you can pass your event loop if any :)
Related commit: https://github.com/graphql-python/graphql-core/commit/3258d297a877d0215764a28f281698b8bdd6b6b2

Closing the issue. Please reopen if you run into any other problems with this.

**Comment by AlecAivazis** [comment]
So it seems the particular bug has been fixed, unfortunately I'm still unable to successfully execute a query with the asyncio executor.  Here is my test case:

``` python
import asyncio
import graphene
from graphql.execution.executors.asyncio import AsyncioExecutor

# get the current event loop
loop = asyncio.get_event_loop()

class Query(graphene.ObjectType):
    hello = graphene.String()

    @asyncio.coroutine
    def resolve_hello(self, *args, **kwds):
        return 'world'

schema = graphene.Schema(
    query=Query,
    executor=AsyncioExecutor(loop=loop)
)


result = schema.execute("""
    query {
        hello
    }
 """)

print(result.data)
```

Which results in:

```
OrderedDict([('hello', '<generator object Query.resolve_hello at 0x10b3844c0>')])
```

I might be doing something wrong - if i'm understanding the source code correctly, wrapping the resolver in `@asyncio.coroutine` should be enough to have the future yielded, right? That doesn't seem to be happening...

**Comment by AlecAivazis** [comment]
Any news on this @syrusakbary?

**Comment by syrusakbary** [comment]
Probably it's because `@asyncio.coroutine`... let me take a better look later today!

**Comment by syrusakbary** [comment]
Hey @AlecAivazis this should be solved now... let me know if everything works perfectly!

**Comment by steveklewis** [comment]
I'm still getting the behavior that just returns a string ('<generator object ...>') and it looks like I'm using the latest with the commit code referenced here. I'm using Python 3.5.2. Here are the versions of things I'm using:

asyncio (3.4.3)
Cython (0.24.1)
graphene (0.10.2)
graphql-core (0.5.3)
graphql-relay (0.4.4)
iso8601 (0.1.11)
pip (8.1.2)
promise (0.4.2)
setuptools (20.10.1)
six (1.10.0)

Thanks in advance. I didn't see @AlecAivazis reply that he got it working so I wanted to put in my data point.

**Comment by steveklewis** [comment]
I'm still seeing the behavior just returning the string. I'm using Python 3.5.2 with these libs:

asyncio (3.4.3)
Cython (0.24.1)
graphene (0.10.2)
graphql-core (1.0)
graphql-relay (0.4.4)
iso8601 (0.1.11)
pip (8.1.2)
promise (0.4.2)
setuptools (20.10.1)
six (1.10.0)

It looks like I have the latest code if I go into site-packages but maybe there's something dumb I'm doing. Just wanted to put in my $.02 cents since @AlecAivazis didn't reply that it was working for him, in case this helps you.

**Comment by bcb** [comment]
Seems to work for me @steveklewis

``` py
import asyncio
import graphene
from graphql.execution.executors.asyncio import AsyncioExecutor

class Query(graphene.ObjectType):
    hello = graphene.String(description='Hello')

    async def resolve_hello(self, *args, **kwds):
        return 'world'

schema = graphene.Schema(query=Query)
executor = AsyncioExecutor(loop=asyncio.get_event_loop())
result = schema.execute('{hello}', executor=executor)

print(result.data)
```

Results in

``` sh
OrderedDict([('hello', 'world')])
```

**Comment by japrogramer** [comment]
I get an error


```
            result = schema.execute(
                          payload['query'],
                          variable_values=payload['variables'],
                          root_value=rx.Observable.create(stream).share(),
                          allow_subscriptions=True,
                          executor=AsyncioExecutor(loop=asyncio.get_event_loop()),
                          **{'context_value': message})
```

```
    async def resolve_sub_product(self, info, **input):
        await make_sub(info, input.get('product'))
        name = ProductType._meta.model.__class__.__name__
        subscribe = info.context['subscribe']
        if subscribe:
            subscribe(name)

        stream = info.root_value
        return stream.map(lambda message: self.next(message, info, **input))

```
 ```
     (Pdb) result.errors
            [RuntimeError('This event loop is already running',)]
```

**Comment by japrogramer** [comment]
I made some more changes and believe i am closer 

```
            result = await graphql(schema,
                          payload['query'],
                          variable_values=payload['variables'],
                          root_value=rx.Observable.create(stream).share(),
                          allow_subscriptions=True,
                          executor=AsyncioExecutor(loop=asyncio.get_event_loop()),
                          **{'context_value': message})

```

```
[2018/06/10 03:20:35] HTTP POST /graphql 200 [0.04, 10.0.0.4:48010]
> /app/apple/graphquery/consumers.py(75)websocket_receive()
-> result = await graphql(schema,
(Pdb) c
> /app/apple/product/schema.py(179)resolve_sub_product()
-> await make_sub(info, input.get('product'))
(Pdb) n
> /app/apple/product/schema.py(180)resolve_sub_product()
-> name = ProductType._meta.model.__class__.__name__
(Pdb) n
> /app/apple/product/schema.py(182)resolve_sub_product()
-> stream = info.root_value
(Pdb) n
> /app/apple/product/schema.py(183)resolve_sub_product()
-> return stream.map(lambda message: self.next(message, info, **input))
(Pdb) n
2018-06-10 03:20:43,619 - ERROR - server - Exception inside application: object ExecutionResult can't be used in 'await' expression
  File "/usr/local/lib/python3.6/site-packages/channels/sessions.py", line 175, in __call__
    return await self.inner(receive, self.send)
  File "/usr/local/lib/python3.6/site-packages/channels/consumer.py", line 54, in __call__
    await await_many_dispatch([receive, self.channel_receive], self.dispatch)
  File "/usr/local/lib/python3.6/site-packages/channels/utils.py", line 50, in await_many_dispatch
    await dispatch(result)
  File "/usr/local/lib/python3.6/site-packages/channels/consumer.py", line 67, in dispatch
    await handler(message)
  File "/app/apple/graphquery/consumers.py", line 75, in websocket_receive
    result = await graphql(schema,
  object ExecutionResult can't be used in 'await' expression
[2018/06/10 03:20:43] WebSocket DISCONNECT /gql [10.255.0.2:52896]


```

**Comment by blazewicz** [comment]
@japrogramer you propably found solution already but I think this issue requires some conclusion

`schema.execute()` with default value of `return_promise` - a `False` - will fail in asyncio context (when run from a coroutine) with "Event loop already running" Exception. This is because `execute` internally calls `wait_until_finished()` which always tries to start the loop. Puropose of this function is to run coroutines asynchronously in synchronous context. This is why example shown by @bcb works.

Solution for your case - running AsyncioExecutor from asyncio context - is shown in #67. Simply add `return_promise=True` to call to `execute` and you'll receive a Promise which you can `await` in your coroutine.
